graph TB

subgraph Networking
  http2((HTTP/2))
end

subgraph server
  serverApp(gRPC Service implementation)
  serverApp --- SDL("Generated gRPC Service/ ProtoBuff Message Defintion")
  ServerInterceptor("Server Interceptor") -.-> serverApp
  subgraph server Lib
    SDL
    gRPCserverHandler["Server gRPC Call Hander"] --> ServerInterceptor
    ServerTransport["Transport(Netty Web Server)"] --> gRPCserverHandler
  end
end

subgraph client
    clientApp(client app code) ---|call| stub
    clientApp(client app code) ---|async call| FutureStub
    clientApp(client app code) ---|call| BlockingStub
    subgraph client Lib
      stub --> gRPCClientInvocation(gRPC invocation)
      FutureStub --> gRPCClientInvocation
      BlockingStub --> gRPCClientInvocation
      gRPCClientInvocation --> ClientInterceptor("Client Interceptor")
      ClientInterceptor -.-> Channel
      Channel --> ClientTransport["Transport(Netty Web Server)"]
    end
end

ClientTransport ==> http2
http2 ==> ServerTransport
ServerTransport ==> http2
http2 ==> ClientTransport
