graph TB

subgraph Networking
  http2((HTTP/2))
end

subgraph server
  serverApp(gRPC Service implementation)
  serverApp --- SDL("Generated gRPC Service/ ProtoBuff Message Defintion")
  Interceptor -.-> serverApp
  subgraph server Lib
    SDL
    gRPCserverHandler(Server gRPC Call Hander) --> Interceptor
    ServerTransport["Transport(Netty Web Server)"] --> gRPCserverHandler
  end
end

subgraph client
    clientApp(client app code) ---|call| stub
    clientApp(client app code) ---|async call| FutureStub
    clientApp(client app code) ---|call| BlockingStub
    subgraph client Lib
      stub --> gRPCClientInvoke(gRPC invocation)
      FutureStub --> gRPCClientInvoke
      BlockingStub --> gRPCClientInvoke
      gRPCClientInvoke -.-> Channel
      Channel --> ClientTransport["Transport(Netty Web Server)"]
    end
end

ClientTransport ==> http2
http2 ==> ServerTransport
ServerTransport ==> http2
http2 ==> ClientTransport
